version: "3.8"
services:
    redis:
        image: redis
        container_name: notification-redis
        ports:
            - 8078:6379
        networks:
            - notification_network
        restart: unless-stopped
    noti:
        image: sihc/notification-service:${IMAGE_TAG}
        container_name: notification-service
        build:
            context: ..
            dockerfile: docker/Dockerfile
        env_file:
            - .env
        environment:
            - NS_REDIS_HOST=redis
        ports:
            - 587:587
        depends_on:
            - redis
        networks:
            - notification_network
        restart: unless-stopped
networks:
    notification_network:
        name: notification_network
